// <auto-generated />
namespace BookLibrary.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_object_category_key_to_int_step_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_object_category_key_to_int_step_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201801311446270_change_object_category_key_to_int_step_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
