// <auto-generated />
namespace BookLibrary.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_entry_type_to_book : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_entry_type_to_book));
        
        string IMigrationMetadata.Id
        {
            get { return "201801041408325_add_entry_type_to_book"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
