// <auto-generated />
namespace BookLibrary.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_object_category_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_object_category_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201802011703266_remove_object_category_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
