// <auto-generated />
namespace BookLibrary.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class replace_book_categories_with_object_categories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(replace_book_categories_with_object_categories));
        
        string IMigrationMetadata.Id
        {
            get { return "201801111642570_replace_book_categories_with_object_categories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
