// <auto-generated />
namespace BookLibrary.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_starring_string_to_movie : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_starring_string_to_movie));
        
        string IMigrationMetadata.Id
        {
            get { return "201801181534296_add_starring_string_to_movie"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
