// <auto-generated />
namespace BookLibrary.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class unknown_mig_1_20180212 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(unknown_mig_1_20180212));
        
        string IMigrationMetadata.Id
        {
            get { return "201802121653515_unknown_mig_1_20180212"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
