// <auto-generated />
namespace BookLibrary.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_manually_added_to_movie_star : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_manually_added_to_movie_star));
        
        string IMigrationMetadata.Id
        {
            get { return "201801181654193_add_manually_added_to_movie_star"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
