// <auto-generated />
namespace BookLibrary.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class artist_model_cleanup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(artist_model_cleanup));
        
        string IMigrationMetadata.Id
        {
            get { return "201802131252452_artist_model_cleanup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
