// <auto-generated />
namespace BookLibrary.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class undefined_migration_20180125 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(undefined_migration_20180125));
        
        string IMigrationMetadata.Id
        {
            get { return "201801251508359_undefined_migration_20180125"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
