// <auto-generated />
namespace BookLibrary.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_tv_shows : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_tv_shows));
        
        string IMigrationMetadata.Id
        {
            get { return "201802131945162_add_tv_shows"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
